// app/terms/page.tsx
"use client";

import AppHeader from "@/app/components/AppHeader";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-100 flex flex-col">
      <AppHeader />

      <div className="flex-1">
        <div className="max-w-3xl mx-auto px-4 py-8 md:py-12 text-sm">
          <h1 className="text-2xl md:text-3xl font-bold mb-3">
            Terms of Use
          </h1>
          <p className="text-xs md:text-sm text-slate-400 mb-6">
            Last updated: {new Date().toISOString().split("T")[0]}
          </p>

          <div className="space-y-4 text-[13px] leading-relaxed text-slate-200">
            <p>
              By using AI Productivity Hub, you agree to these terms. If you
              do not agree, please do not use the service.
            </p>

            <h2 className="text-sm font-semibold mt-4">
              1. Service description
            </h2>
            <p>
              AI Productivity Hub is a personal productivity tool that helps
              you manage notes, tasks, daily scores, weekly goals, and
              optional travel plans, with AI-powered assistance.
            </p>

            <h2 className="text-sm font-semibold mt-4">
              2. No guarantees
            </h2>
            <p>
              This app is provided on an &quot;as is&quot; and &quot;as
              available&quot; basis. We do not guarantee that the service
              will be always available, bug-free, or that AI outputs will be
              accurate, complete, or suitable for any particular purpose.
            </p>

            <h2 className="text-sm font-semibold mt-4">3. Your account</h2>
            <p>
              You are responsible for keeping your login details secure and
              for all activity under your account. Please use a strong
              password and do not share it with others.
            </p>

            <h2 className="text-sm font-semibold mt-4">
              4. Acceptable use
            </h2>
            <p>
              You agree not to use the app to store or generate illegal,
              abusive, or harmful content. We may suspend or terminate access
              if we detect misuse, abuse, or attempts to attack the service.
            </p>

            <h2 className="text-sm font-semibold mt-4">
              5. AI-generated content
            </h2>
            <p>
              Suggestions and content generated by AI are for informational
              and productivity purposes only. They should not be treated as
              professional advice (for example medical, legal, or financial).
              You are responsible for how you use the information.
            </p>

            <h2 className="text-sm font-semibold mt-4">
              6. Paid plans & billing
            </h2>
            <p>
              If you upgrade to a paid plan, billing is handled securely by
              our payment provider (for example Stripe). Plan details,
              pricing, and limits may change over time; any changes will
              usually be reflected in the pricing section of the site.
            </p>

            <h2 className="text-sm font-semibold mt-4">
              7. Changes to the service
            </h2>
            <p>
              We may update or change features, limits, or the design of the
              app. We may also update these Terms from time to time. If the
              changes are material, we&apos;ll try to highlight them in the
              app or changelog.
            </p>

            <h2 className="text-sm font-semibold mt-4">
              8. Limitation of liability
            </h2>
            <p>
              To the maximum extent permitted by law, we are not liable for
              any indirect, incidental, or consequential damages arising from
              your use of the service, including any decisions made based on
              AI suggestions.
            </p>

            <h2 className="text-sm font-semibold mt-4">
              9. Contact
            </h2>
            <p>
              If you have questions about these terms, you can reach us via
              the Feedback page inside the app or the support email shown
              there.
            </p>

            <p className="text-[11px] text-slate-500 mt-4">
              This is a simple, human-readable terms page and does not
              replace proper legal review. For a commercial launch, consider
              asking a lawyer to review and adapt these terms for your
              specific situation.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
