// app/terms/page.tsx
"use client";

import AppHeader from "@/app/components/AppHeader";
import { useT } from "@/lib/useT";

export default function TermsPage() {
  const { t } = useT("terms");
  const lastUpdated = new Date().toISOString().split("T")[0];

  return (
    <main className="min-h-screen bg-[var(--bg-body)] text-[var(--text-main)] flex flex-col">
      <AppHeader active="settings" />

      <div className="flex-1">
        <div className="max-w-3xl mx-auto px-4 py-8 md:py-12 text-sm">
          <header className="mb-6">
            <h1 className="text-2xl md:text-3xl font-bold mb-2">
              {t("terms.title", "Terms of Use")}
            </h1>
            <p className="text-xs md:text-sm text-[var(--text-muted)]">
              {t("terms.lastUpdatedLabel", "Last updated")}: {lastUpdated}
            </p>
          </header>

          <section className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-card)] px-4 sm:px-5 py-5 text-[13px] leading-relaxed text-[var(--text-main)] space-y-4">
            <p>
              {t(
                "terms.intro",
                "By using AI Productivity Hub, you agree to these terms. If you do not agree, please do not use the service."
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section1.title", "1. Service description")}
            </h2>
            <p>
              {t(
                "terms.section1.body",
                "AI Productivity Hub is a personal productivity tool that helps you manage notes, tasks, daily scores, weekly goals, and optional travel plans, with AI-powered assistance."
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section2.title", "2. No guarantees")}
            </h2>
            <p>
              {t(
                "terms.section2.body",
                'This app is provided on an "as is" and "as available" basis. We do not guarantee that the service will be always available, bug-free, or that AI outputs will be accurate, complete, or suitable for any particular purpose.'
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section3.title", "3. Your account")}
            </h2>
            <p>
              {t(
                "terms.section3.body",
                "You are responsible for keeping your login details secure and for all activity under your account. Please use a strong password and do not share it with others."
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section4.title", "4. Acceptable use")}
            </h2>
            <p>
              {t(
                "terms.section4.body",
                "You agree not to use the app to store or generate illegal, abusive, or harmful content. We may suspend or terminate access if we detect misuse, abuse, or attempts to attack the service."
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section5.title", "5. AI-generated content")}
            </h2>
            <p>
              {t(
                "terms.section5.body",
                "Suggestions and content generated by AI are for informational and productivity purposes only. They should not be treated as professional advice (for example medical, legal, or financial). You are responsible for how you use the information."
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section6.title", "6. Paid plans & billing")}
            </h2>
            <p>
              {t(
                "terms.section6.body",
                "If you upgrade to a paid plan, billing is handled securely by our payment provider (for example Stripe). Plan details, pricing, and limits may change over time; any changes will usually be reflected in the pricing section of the site."
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section7.title", "7. Changes to the service")}
            </h2>
            <p>
              {t(
                "terms.section7.body",
                "We may update or change features, limits, or the design of the app. We may also update these Terms from time to time. If the changes are material, we'll try to highlight them in the app or changelog."
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section8.title", "8. Limitation of liability")}
            </h2>
            <p>
              {t(
                "terms.section8.body",
                "To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including any decisions made based on AI suggestions."
              )}
            </p>

            <h2 className="text-sm font-semibold mt-4">
              {t("terms.section9.title", "9. Contact")}
            </h2>
            <p>
              {t(
                "terms.section9.body",
                "If you have questions about these terms, you can reach us via the Feedback page inside the app or the support email shown there."
              )}
            </p>

            <p className="text-[11px] text-[var(--text-muted)] mt-4">
              {t(
                "terms.disclaimer",
                "This is a simple, human-readable terms page and does not replace proper legal review. For a commercial launch, consider asking a lawyer to review and adapt these terms for your specific situation."
              )}
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
